import type { Experience } from "./types";

const residence: Experience = {
  slug: "residence",
  name: "Résidence",
  ready: true,
  frameCount: 367,
  keyframes: [
    {
      id: "RES1",
      at: 0,
      scene: "Vue aérienne au coucher du soleil, la résidence et ses jardins",
      label: "Résidence Les Tilleuls",
      colors: ["#F2B880", "#D98A6A", "#4B5A3E"],
      light: { x: 0.75, y: 0.3, color: "#FFD9A0" },
    },
    {
      id: "RES2",
      at: 0.159,
      scene: "Entrée vitrée, hall lumineux en bois clair",
      label: "Accueil",
      colors: ["#F3E6D3", "#D9BFA0", "#8A6A4E"],
      light: { x: 0.5, y: 0.35, color: "#FFF3DC" },
    },
    {
      id: "RES3",
      at: 0.309,
      scene: "Couloir, infirmière de dos avec sa tablette",
      label: "Poste de soins",
      colors: ["#E3ECF5", "#B9C9DA", "#6D7E92"],
      light: { x: 0.5, y: 0.4, color: "#FFFFFF" },
    },
    {
      id: "RES4",
      at: 0.458,
      scene: "Cabinet médical, médecin de dos à son bureau",
      label: "Cabinet médical",
      colors: ["#E8EFE6", "#BFCDB8", "#5F6E5A"],
      light: { x: 0.8, y: 0.35, color: "#F7FFF0" },
    },
    {
      id: "RES5",
      at: 0.607,
      scene: "Sortie par la fenêtre, la ville au crépuscule",
      label: "Vers la ville",
      colors: ["#2E3A63", "#C97A5D", "#1E2436"],
      light: { x: 0.3, y: 0.55, color: "#FFB37A" },
    },
    {
      id: "RES6",
      at: 0.735,
      scene: "Appartement le soir, Claire lit son téléphone",
      label: "Chez Claire",
      colors: ["#2A2F45", "#8C5A3C", "#1B1A22"],
      light: { x: 0.65, y: 0.45, color: "#FFC27A" },
    },
    {
      id: "RES7",
      at: 0.863,
      scene: "Recul aérien à l’heure bleue, lac et montagnes",
      label: "Le soir venu",
      colors: ["#1D2C55", "#3E5A8A", "#0F1729"],
      light: { x: 0.5, y: 0.62, color: "#FFD9A8" },
    },
  ],
  cards: [
    {
      id: "hero",
      type: "hero",
      at: [0, 0.1],
      eyebrow: "Résidence · EMS",
      title: "Chaque information, à la bonne personne.",
      text: "CareBond relie l'équipe soignante, les médecins et les familles, en temps réel.",
    },
    {
      id: "observation",
      type: "app",
      at: [0.27, 0.44],
      side: "left",
      tag: "Équipe soignante",
      title: "Observation · Chambre 12",
      subtitle: "Mme Jeanne Morel, 86 ans",
      fields: [
        { k: "TA", v: "135/80" },
        { k: "Temp.", v: "37,1 °C" },
      ],
      lines: ["Bon appétit au petit-déjeuner", "Toux légère depuis ce matin"],
      meta: "Sophie B., infirmière · 10:42",
      button: { label: "Transmettre au médecin", sentLabel: "Transmis au médecin" },
      send: { to: "push-doctor", at: [0.38, 0.44] },
    },
    { id: "push-doctor", type: "push", at: [0.44, 0.5], side: "right" },
    {
      id: "reply-doctor",
      type: "reply",
      at: [0.47, 0.59],
      side: "right",
      author: "Dr Marc Aubert",
      role: "Médecin",
      time: "10:51",
      body: "Vu. Je passe la voir à 14 h pour l’ausculter.",
    },
    { id: "push-family", type: "push", at: [0.69, 0.75], side: "right" },
    {
      id: "family",
      type: "app",
      at: [0.73, 0.85],
      side: "right",
      tag: "Famille",
      title: "Résidence Les Tilleuls · 11:05",
      body: "Bonjour Claire, votre maman va bien. Elle tousse un peu depuis ce matin : le Dr Aubert passe la voir cet après-midi. Nous vous tenons informée.",
    },
    {
      id: "cta",
      type: "cta",
      at: [0.9, 1],
      title: "Voir CareBond en action.",
      button: "Demander une démo",
      href: "https://www.carebond.ch/fr/contact",
    },
  ],
};

export default residence;
